export interface Probe {
  probePrefix:string;
  probeURL:string;
  interval:number;
  port:number;
  method:string;
  locations:Array<string>; 
  notify:boolean;
  notificationPolicyId?:string;
  policyChoice?:string;
  matchPolicy?:{
    keywords:string[],
    matchAll:boolean
  };
  policy?:string;
  requestBody?:string;
  requestBodyJson?:boolean;
  headers?:[{
    key:string,
    value:string
  }?];
  basicAuth?:{
    user:string,
    password:string
  }
}
